### PR TITLE
Update to Angular 2.4

### PR DESCRIPTION
**Pull request by cmckni3**
Things left:

- [x] Build and deploy scripts (rollup, npm, etc)
- [x] Running the demo is finicky due to the lodash dependency. `@angular/cli` fails to compile "Unable to find module 'lodash'"
- [x] Make sure rollup build works in a project
- [x] Demo styles
- [ ] Review the README

### CODE REVIEW

**Comment by cmckni3** [comment]
Let me know if the README needs some updates. I glanced over it quickly.

**Comment by cmckni3** [comment]
@andyperlitch Everything looks good on my end. I was able to build the library and use the built library in a sample `@angular/cli` application. I also fixed the issue with `lodash` by installing `@types/lodash`.

Do you have a way to try it out in an application that does not use a module bundler?

**Comment by andyperlitch** [comment]
All in all, looks great. Do you think we can use `package-lock.json` instead of `yarn-lock.json`? It's `npm`'s response to yarn, and works the same way as i understand it.

**Comment by cmckni3** [comment]
I prefer `yarn` because it's still faster than the latest version of `npm`. We can include both for the project.

It's a little confusing but the `package.json` and `yarn.lock` in the root folder are for the demo project itself.

**Comment by cmckni3** [comment]
@andyperlitch Added `package-lock.json` for `npm` users.

**Comment by cmckni3** [comment]
Andddd it doesn't work when using `npm install`

**Comment by cmckni3** [comment]
@andyperlitch Good to go now. `npm` 5.2.0 is broken.

**Comment by cmckni3** [comment]
I am working on a fix for the rollup warnings. Adding missing external and globals to the rollup config.

**Comment by andyperlitch** [comment]
I'm attempting to resolve the test failures. Currently I am up against failures in `app.component.spec.ts`. Looks like it is angry about dynamically-added components not being in `entryComponents`. I have found myself perusing [this issue](https://github.com/angular/angular/issues/10760) on angular. No obvious fix found yet.

**Comment by cmckni3** [comment]
Hmm, I never ran the test suite. The module in the spec file probably needs `entryComponents` set with `InstrumentComponent`.

**Comment by cmckni3** [comment]
Ah yeah it's a little different actually. Have to use `overrideModule`.

**Comment by andyperlitch** [comment]
`npm run release` actually runs the tests, which is where i was snagged.

You must be reading the same comments i am. I tried this:

```typescript
import { TestBed, async } from '@angular/core/testing';
import { BrowserDynamicTestingModule } from '@angular/platform-browser-dynamic/testing';

import { AppComponent } from './app.component';
import { DemoComponent } from './demo.component';
import { SuperTableModule } from '../lib';
import { InstrumentComponent } from './instrument.component';

describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent,
        DemoComponent,
        InstrumentComponent
      ],
      imports: [
        SuperTableModule
      ]
    }).compileComponents();
    TestBed.overrideModule(BrowserDynamicTestingModule, {
      set: {
        entryComponents: [InstrumentComponent]
      }
    });
  }));
// ...
```

but still no luck...

**Comment by cmckni3** [comment]
PR incoming to fix demo tests and e2e tests

**Comment by cmckni3** [comment]
I actually have a bunch of tests in my current app at work that use `ng-bootstrap` and require `overrideModule`.

**Comment by cmckni3** [comment]
Let me know if you have any issues publishing to npmjs.org, @andyperlitch.

**Comment by andyperlitch** [comment]
Sent a few messages on the Gitter channel

**Comment by cmckni3** [comment]
I just missed them earlier.

**Pull request merged**
